Repository JjungminLee/YourSSU-RealWorld-SK, pull requests merged in 2023-07, with the labels that each got.

#22 feat: 좋아요 기능 구현
  src/apis/articles.ts
  src/components/Home/atoms/ArticlePreview.tsx
  src/components/Home/atoms/LikeButton.tsx
  src/components/Home/index.tsx
  src/hooks/useGetArticles.ts
  src/hooks/usePostFavorite.ts
  src/types/articles.ts
Labels: enhancement

#35 profile 페이지 수정
  src/apis/articles.ts
  src/apis/user.ts
  src/components/Home/atoms/ArticlePreview.tsx
  src/components/Home/atoms/Profile.tsx
  src/components/login/index.tsx
  src/components/profile/index.tsx
  src/components/profile/myArticleItem.tsx
  src/types/user.ts
Labels: FIX

#41 FEAT: 태그 필터 기능
  src/components/Home/atoms/PopularTag.tsx
  src/components/Home/index.tsx
  src/components/common/Pagination.tsx
  src/components/common/PaginationButton.tsx
  src/states/pageState.ts
  src/states/tagState.ts
Labels: FEAT

#44 회원가입 예외처리
  src/App.tsx
  src/apis/common.ts
  src/apis/user.ts
  src/components/article/index.tsx
  src/components/login/index.tsx
  src/components/settings/index.tsx
  src/components/signUp/index.tsx
  src/states/UserAtom.ts
Labels: FIX

#45 Feat:글 상세조회 페이지
  src/App.tsx
  src/apis/articles.ts
  src/components/Home/atoms/ArticlePreview.tsx
  src/components/article/index.tsx
  src/components/editArticle/index.tsx
  src/components/profile/index.tsx
  src/components/profile/myArticleItem.tsx
  src/types/articles.ts
Labels: FEAT

#48 FIX : 버그 수정
  index.html
  src/App.tsx
  src/apis/articles.ts
  src/apis/user.ts
  src/components/Home/atoms/ArticlePreview.tsx
  src/components/article/index.tsx
  src/components/profile/index.tsx
  src/components/profile/myArticleItem.tsx
  src/hooks/useGetProfile.ts
  src/hooks/usePostFollow.ts
  src/hooks/usePostUnfollow.ts
Labels: bug, FIX
